### ISSUE TITLE
TRN-SAP-BYD004 - ( Online class )

### ISSUE THREAD

**Issue by astpl1998** [astpl1998/Training#1]
Please Schedule the Batch from 14-3-2019

**Comment by srinivasanbaskaran** [comment]
Latest updated Training Schedule 

[Nirmala Training Schedule - Updated - BYD-004.xlsx](https://github.com/astpl1998/Training/files/3185581/Nirmala.Training.Schedule.-.Updated.-.BYD-004.xlsx)

**Comment by srinivasanbaskaran** [comment]
This Training has been dropped..

Hence this Training has been closed
