### ISSUE TITLE
KSS: Knowledge Sharing Session on Process Production - Nova

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Training#160]
Dear Nova,

Please attach the relavant documents about this ticket

Regards,
Srinivasan Baskaran

**Comment by knovakaspar** [comment]
Dear Srini,

As per the First Session, Process Production Master's and Kanam Automation logic's has been completed. Pls find attached for which was done.

[Process Production Master's- Knowledge Transfer session(260621).xlsx](https://github.com/astpl1998/Training/files/6725146/Process.Production.Master.s-.Knowledge.Transfer.session.260621.xlsx)

Regards
Nova K

**Comment by srinivasanbaskaran** [comment]
@knovakaspar ,

Please update all the Recordings into this Github Ticket. 

Regards,
Srinivasan Baskaran

**Comment by knovakaspar** [comment]
@srinivasanbaskaran 

Pls find the session detail for your reference.
[Knowledge Transfer - Session details.xlsx](https://github.com/astpl1998/Training/files/6878699/Knowledge.Transfer.-.Session.details.xlsx)

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The training is completed.
Kindly close the ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Training completed so closing this ticket
