### ISSUE TITLE
KSS : Session on Project Management

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Training#161]
Dear All, 

Session on Project Management which is available in our product.

Herewith I have attached the link of the Recorded Session. 

PRESENTATION: [Project Management_PPT.pptx](https://github.com/astpl1998/Training/files/6788779/Project.Management_PPT.pptx)

LINK: https://transcripts.gotomeeting.com/#/s/e8686769738abbab20e8f4808674ace44f66843dd02906cc6692baac10e81169

Regards,
Srinivasan Baskaran

**Comment by eafaisal** [comment]
@raju-kurup Sir,

The training is completed.
Kindly close the ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment]
Training completed so closing this ticket
