### ISSUE TITLE
SAP-BYD006 - Procurement Planning

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Training#36]
#32

An   Introduction to Procurement Planning

Procurement Process

1. STOCK ABLE

2.NON- STOCK ABLE

**Comment by srinivasanbaskaran** [comment]
Stockable completed.

Non Stockable is pending

**Comment by srinivasanbaskaran** [comment]
Team,

Non Stockable Purchase Completed on 19-07-2019...

Hands On need to be completed ( By Students) ....

Regards,

Srinivasan Baskaran
