### ISSUE TITLE
SAP-BYD006 - PRODCUTION

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Training#40]
#32

An   Introduction to Production Module, Uses in Decision Making

1.Production Planning
2.Outsourcing to Complete
3.Decision Making on Produce 
4.Production Process

**Comment by srinivasanbaskaran** [comment]
1.Production Planning
2.Outsourcing to Complete
3.Production Process

---- Above mentioned topics are completed.. 

Decision Making on Produce is the only pending .... And Hands On to be completed....

**Comment by srinivasanbaskaran** [comment]
Closed
