### ISSUE TITLE
SAP-BYD006 - Core Finance

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Training#41]
#32

Core Finance

1.Accounts   Payable
2.Accounts Receivable
3.General Ledger Accounting
4.Liquidity Management

**Comment by srinivasanbaskaran** [comment]
1. Account Receivables 
2. Account Payables 
3. Cash & Liquidity Management 

-- are completed

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
General Accouting Ledger only pending

**Comment by srinivasanbaskaran** [comment]
General Ledger & Accounting theory has been completed..

Practical is only pending..

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Closed
