### ISSUE TITLE
SAP-BYD007 - PROCUREMENT PLANNING

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Training#48]
#35

An   Introduction to Procurement Planning

Procurement Process

1.Stock-able
2.Non stock-able

**Comment by knovakaspar** [comment]
Dear Srini...

Purchase module completed...


Regards
Nova

**Comment by knovakaspar** [comment]
Dear srini....

                   Pending hands on...

Regards
Nova

**Comment by srinivasanbaskaran** [comment]
Below Hands On are completed.. 

1. Masters ( Product, Supplier & Customer )
2. Procure to Pay Scenario 

Regards,

Srinivasan Baskaran
