### ISSUE TITLE
SAP-BYD007 - PRODCUTION

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Training#52]
#35

An   Introduction to Production Module

1.Uses in Decision Making
2.Production Planning or Outsourcing to Complete, Decision Making on Produce
3.Production Process

**Comment by srinivasanbaskaran** [comment]
1.Production Planning
2.Outsourcing to Complete
3.Production Process

---- Above mentioned topics are completed..

Decision Making on Produce is the only pending .... And Hands On to be completed....

**Comment by srinivasanbaskaran** [comment]
Completed...

Handson needs to be completed....

**Comment by srinivasanbaskaran** [comment]
Completed...

Hence this ticket has been closed

Regards,

Srinivasan Baskaran
