### ISSUE TITLE
SAP-BYD007 - PURCHASE MODULE (NON STOCK )

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Training#53]
#35

Procure   to Pay ( Non Stock )

An Introduction to Inventory Mgmt
Inventory - Planning

**Comment by srinivasanbaskaran** [comment]
Team,

Non Stockable Purchase Completed...

Hands On need to be completed ( By Students) ....

**Comment by srinivasanbaskaran** [comment]
Hence this ticket closed
