### ISSUE TITLE
TRN - AKASH RAMCO ERP TRAINNING

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Training#59]

**Comment by srinivasanbaskaran** [comment]
This ticket is for Training to Akash.

Training Schedule attached... Training starts on 15-07-2019

[Ramco Training Schedule -Akash.xlsx](https://github.com/astpl1998/Training/files/3378721/Ramco.Training.Schedule.-Akash.xlsx)

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Nova,

Kindly start the Training & update the status by every last working day of the week.

Regards,

Srinivasan Baskaran

**Comment by knovakaspar** [comment]
Dear srini

               As per schedule,
1.Introduction to ERP.
2.Implementation stages.
3.Masters(Inventory & picc).
[Ramco.Training.Schedule.-Akash.xlsx](https://github.com/astpl1998/Training/files/3400313/Ramco.Training.Schedule.-Akash.xlsx)

4.masters(purchase & subcontracting).
               Topics are covered. please find attached for latest training schedule.

Regards
Nova

**Comment by knovakaspar** [comment]
Dear srini,

                As per schedule
1.sales and shipping(masters)completed.
2.purchase normal flow(in progress)

Regards,
Nova
[Ramco.Training.Schedule.-Akash.xlsx](https://github.com/astpl1998/Training/files/3410954/Ramco.Training.Schedule.-Akash.xlsx)


Purchase - Normal flow
--




Sales   & Shipping
--



Sales   & Shipping
--

**Comment by knovakaspar** [comment]
Dear srini,

               As per schedule,
1.Inventory management completed.


Regards,
Nova
[Ramco.Training.Schedule.-Akash.xlsx](https://github.com/astpl1998/Training/files/3416998/Ramco.Training.Schedule.-Akash.xlsx)

**Comment by Dhanwandher** [comment]
Book Keeping,Payable Management & Receivable Management completed.
Master Definition
1. Account Code Creation
2. ARD
3. Bank Creation


1.  Purchase Invoice Creation
2. supplier Payment
3. Supplier Debit Credit Note
4. Supplier Balance Adjustment
5. Supplier Reports

1. Sale Invoice Creation
2. Customer Receipt
3. Customer Debit Credit Note
4. Customer Balance Adjustment
5. Customer Reports

Regards.
S.Dhanwandher.
[Ramco Training-Akash.xlsx](https://github.com/astpl1998/Training/files/3454902/Ramco.Training-Akash.xlsx)

**Comment by Dhanwandher** [comment]
General ledger,Masters Completed

JVs
Calendar Creation
Period Closure
Bank Reconcilation

Regards.
S.Dhanwandher
[Ramco Training-Akash.xlsx](https://github.com/astpl1998/Training/files/3454967/Ramco.Training-Akash.xlsx)

**Comment by Dhanwandher** [comment]
Supplier Balance transfer and Customer Balance transfer completed.....

MAC still pending.......


Regards...
S.Dhanwandher....

**Comment by srinivasanbaskaran** [comment]
[Ramco_Training_Updated-Akash.xlsx](https://github.com/astpl1998/Training/files/3661264/Ramco_Training_Updated-Akash.xlsx)

**Comment by srinivasanbaskaran** [comment]
[Ramco Training Schedule Updated on 30919 -Akash.xlsx](https://github.com/astpl1998/Training/files/3668995/Ramco.Training.Schedule.Updated.on.30919.-Akash.xlsx)

**Comment by srinivasanbaskaran** [comment]
Proper tickets created. So this ticket has been closed.

Regards,

Srinivasan Baskaran
