### ISSUE TITLE
SAP - BYD008 - MASTERS

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Training#62]
#60

**Comment by srinivasanbaskaran** [comment]
Following Masters will be taken..

1. Material
2. Customer 
3. Supplier

-----------------

Material & Customer masters has been completed on 05-08-2019

Regards,

Srinivasan Baskaran

**Comment by knovakaspar** [comment]
Dear srini

                As per schedule master module has been completed.

Regards
Nova
