### ISSUE TITLE
SAP-BYD008 - PURCHASE MODULE ( STOCK & NON STOCK)

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Training#68]
#60

**Comment by srinivasanbaskaran** [comment]
Theory wise completed.....

Need to do Hands ON ...

**Comment by srinivasanbaskaran** [comment]
Purchase ( Stock & Non Stock ) completed...

Stockable Purchase completed ( Both Hands ON & Theory )...

Non Stockable Purchase Theory completed ( Hands On Need to be done )

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
All the Procurement related topics ( both Theory & Handson ) are completed.

Hence, this ticket has been closed.

Regards,

Srinivasan Baskaran
