### ISSUE TITLE
SAP-BYD008 - CORE FINANCE

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Training#69]
#60

**Comment by srinivasanbaskaran** [comment]
Account Receivables
Account Payables
Cash & Liquidity Management
-- are completed

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Accounts Payable,
Accounts Receivables,
General Ledger Accounting
Cash Flow Management --- are completed.

Liquidity Management is inly pending

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Liquidity  Management Completed....

Hence this ticket has been closed

Regards,
Srinivasan Baskaran
