### ISSUE TITLE
SAP-BYD008 - FIXED ASSET MANAGEMENT

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Training#71]
#60

**Comment by srinivasanbaskaran** [comment]
Fixed Asset theory completed...

Hands On needs to be done.


Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Theory completed.... 

Hands On Completed...

Regards,
Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Retirement of Assets - also completed..

Regards,

Srinivasan Baskaran
