### ISSUE TITLE
RAM - ERP Training to Manivel & Saravanan

### ISSUE THREAD

**Issue by srinivasanbaskaran** [astpl1998/Training#76]
Training to be on alll the modules

In future, Training Schedule will be updated

Regards,

Srinivasan Baskaran

**Comment by srinivasanbaskaran** [comment]
Training Starts on 13-08-2019 and complete on 14-09-2019

**Comment by srinivasanbaskaran** [comment]
Introduction & Process Flow to be covered on 13-08-2019

**Comment by Dhanwandher** [comment]
Dear Srini.....

Please find the training schedule for manivel and saravanan....

Regards.....
S.Dhanwandher.....
[Ramco Training-Manivel and Saravanan.xlsx](https://github.com/astpl1998/Training/files/3549267/Ramco.Training-Manivel.and.Saravanan.xlsx)

**Comment by srinivasanbaskaran** [comment]
Team,

Kindly start the Training to Manivel & Saravanan along with Akash..

Regards,

Srinivasan Baskaran

**Comment by Dhanwandher** [comment]
Team,

Finance basic training started for Manivel and Saravanan....

Regards.
S.Dhanwandher.

**Comment by srinivasanbaskaran** [comment]
Herewith I have attached Updated Training Schedule .......
[Ramco.Training-Manivel.and.Saravanan.xlsx](https://github.com/astpl1998/Training/files/3669022/Ramco.Training-Manivel.and.Saravanan.xlsx)

**Comment by srinivasanbaskaran** [comment]
Proper tickets created. So this ticket has been closed.

Regards,

Srinivasan Baskaran
